/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.beevou.android;

public final class Manifest {
    public static final class permission {
        /**  GCM messages. 
         */
        public static final String C2D_MESSAGE="com.beevou.android.permission.C2D_MESSAGE";
    }
}
