/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.beevou.android;

public final class R {
    public static final class anim {
        public static final int anim_forever=0x7f040000;
        public static final int flipin=0x7f040001;
        public static final int flipin_reverse=0x7f040002;
        public static final int flipout=0x7f040003;
        public static final int flipout_reverse=0x7f040004;
        public static final int rotate=0x7f040005;
        public static final int rotation=0x7f040006;
        public static final int status_view_animation=0x7f040007;
    }
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int buttonBarButtonStyle=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int buttonBarStyle=0x7f010000;
    }
    public static final class color {
        public static final int black_overlay=0x7f080018;
        public static final int contents_text=0x7f080000;
        public static final int encode_view=0x7f080001;
        public static final int help_button_view=0x7f080002;
        public static final int help_view=0x7f080003;
        public static final int possible_result_points=0x7f080004;
        public static final int result_image_border=0x7f080005;
        public static final int result_minor_text=0x7f080006;
        public static final int result_points=0x7f080007;
        public static final int result_text=0x7f080008;
        public static final int result_view=0x7f080009;
        public static final int sbc_header_text=0x7f08000a;
        public static final int sbc_header_view=0x7f08000b;
        public static final int sbc_layout_view=0x7f08000d;
        public static final int sbc_list_item=0x7f08000c;
        public static final int sbc_page_number_text=0x7f08000e;
        public static final int sbc_snippet_text=0x7f08000f;
        public static final int share_text=0x7f080010;
        public static final int share_view=0x7f080011;
        public static final int status_text=0x7f080013;
        public static final int status_view=0x7f080012;
        public static final int transparent=0x7f080014;
        public static final int viewfinder_frame=0x7f080015;
        public static final int viewfinder_laser=0x7f080016;
        public static final int viewfinder_mask=0x7f080017;
    }
    public static final class drawable {
        public static final int androidform_03=0x7f020000;
        public static final int androidform_04=0x7f020001;
        public static final int androidform_05=0x7f020002;
        public static final int androidform_08=0x7f020003;
        public static final int androidform_09=0x7f020004;
        public static final int androidform_10=0x7f020005;
        public static final int androidform_12=0x7f020006;
        public static final int androidform_13=0x7f020007;
        public static final int androidform_15=0x7f020008;
        public static final int androidform_17=0x7f020009;
        public static final int androidform_18=0x7f02000a;
        public static final int androidform_19=0x7f02000b;
        public static final int androidformbutton_10=0x7f02000c;
        public static final int androidlogin_02=0x7f02000d;
        public static final int androidlogin_03=0x7f02000e;
        public static final int androidlogin_04=0x7f02000f;
        public static final int androidlogin_05=0x7f020010;
        public static final int androidlogin_06=0x7f020011;
        public static final int androidlogin_07=0x7f020012;
        public static final int androidlogin_08=0x7f020013;
        public static final int androidlogin_09=0x7f020014;
        public static final int androidlogin_10=0x7f020015;
        public static final int androidlogin_11=0x7f020016;
        public static final int androidmainmenu_02=0x7f020017;
        public static final int androidmainmenu_03=0x7f020018;
        public static final int androidmainmenu_04=0x7f020019;
        public static final int androidmainmenu_05=0x7f02001a;
        public static final int androidmainmenu_06=0x7f02001b;
        public static final int androidmainmenu_07=0x7f02001c;
        public static final int androidmainmenu_08=0x7f02001d;
        public static final int androidmainmenu_09=0x7f02001e;
        public static final int androidmainmenu_10=0x7f02001f;
        public static final int androidmainmenu_11=0x7f020020;
        public static final int androidmainmenu_12=0x7f020021;
        public static final int androidmainmenu_14=0x7f020022;
        public static final int androidmainmenu_15=0x7f020023;
        public static final int androidmainmenu_16=0x7f020024;
        public static final int arrow_forward=0x7f020025;
        public static final int back32white=0x7f020026;
        public static final int back64=0x7f020027;
        public static final int back64b=0x7f020028;
        public static final int back64white=0x7f020029;
        public static final int beevou100_67_trans=0x7f02002a;
        public static final int beevou223_150=0x7f02002b;
        public static final int beevou223_150_trans=0x7f02002c;
        public static final int beevou50_34_trans=0x7f02002d;
        public static final int beevou_group_252_150=0x7f02002e;
        public static final int beevou_orange_36_29=0x7f02002f;
        public static final int beevou_small_80_54=0x7f020030;
        public static final int beevou_trans_252_150=0x7f020031;
        public static final int bell=0x7f020032;
        public static final int black_button=0x7f020033;
        public static final int black_degraded=0x7f020034;
        public static final int blue_button=0x7f020035;
        public static final int corporate_color_button=0x7f020036;
        public static final int corporate_degraded=0x7f020037;
        public static final int corporate_gray=0x7f020038;
        public static final int corporate_toolbar_delete_108_a=0x7f020039;
        public static final int corporate_toolbar_delete_108_b=0x7f02003a;
        public static final int corporate_toolbar_delete_button=0x7f02003b;
        public static final int corporate_toolbar_find_108_a=0x7f02003c;
        public static final int corporate_toolbar_find_108_b=0x7f02003d;
        public static final int corporate_toolbar_find_button=0x7f02003e;
        public static final int corporate_toolbar_info_108_a=0x7f02003f;
        public static final int corporate_toolbar_info_108_b=0x7f020040;
        public static final int corporate_toolbar_info_button=0x7f020041;
        public static final int corporate_toolbar_lock_108_a=0x7f020042;
        public static final int corporate_toolbar_lock_108_b=0x7f020043;
        public static final int corporate_toolbar_lock_button=0x7f020044;
        public static final int corporate_toolbar_sort_108_a=0x7f020045;
        public static final int corporate_toolbar_sort_108_b=0x7f020046;
        public static final int corporate_toolbar_sort_54_a=0x7f020047;
        public static final int corporate_toolbar_sort_54_b=0x7f020048;
        public static final int corporate_toolbar_sort_button=0x7f020049;
        public static final int corporate_toolbar_transfer_108_a=0x7f02004a;
        public static final int corporate_toolbar_transfer_108_b=0x7f02004b;
        public static final int corporate_toolbar_transfer_button=0x7f02004c;
        public static final int corporate_toolbar_unlock_108_a=0x7f02004d;
        public static final int corporate_toolbar_unlock_108_b=0x7f02004e;
        public static final int corporate_toolbar_unlock_button=0x7f02004f;
        public static final int cutbyline=0x7f020050;
        public static final int days_left_blue=0x7f020051;
        public static final int days_left_darkgray=0x7f020052;
        public static final int days_left_discounted=0x7f020053;
        public static final int days_left_gray=0x7f020054;
        public static final int days_left_green=0x7f020055;
        public static final int days_left_orange=0x7f020056;
        public static final int days_left_red=0x7f020057;
        public static final int delete=0x7f020058;
        public static final int deletevoucher54=0x7f020059;
        public static final int error=0x7f02005a;
        public static final int error128=0x7f02005b;
        public static final int error_fatal_128=0x7f02005c;
        public static final int gear32white=0x7f02005d;
        public static final int gear64white=0x7f02005e;
        public static final int go_right=0x7f02005f;
        public static final int green_button=0x7f020060;
        public static final int grey_button=0x7f020061;
        public static final int ic_action_search=0x7f020062;
        public static final int ic_launcher=0x7f020063;
        public static final int icon_search_54_black=0x7f020064;
        public static final int info64=0x7f020065;
        public static final int launch_icon=0x7f020066;
        public static final int launch_list2_icon=0x7f020067;
        public static final int launch_list_icon=0x7f020068;
        public static final int lockvoucher54=0x7f020069;
        public static final int logout=0x7f02006a;
        public static final int loyalty_icon=0x7f02006b;
        public static final int mainmenu=0x7f02006c;
        public static final int my_account=0x7f02006d;
        public static final int myvouchers=0x7f02006e;
        public static final int noimagevoucher=0x7f02006f;
        public static final int order_by64=0x7f020070;
        public static final int payment_icon=0x7f020071;
        public static final int pin_clear=0x7f020072;
        public static final int purple_button=0x7f020073;
        public static final int qr=0x7f020074;
        public static final int red_button=0x7f020075;
        public static final int refresh_180=0x7f020076;
        public static final int refresh_50=0x7f020077;
        public static final int resendvoucher54=0x7f020078;
        public static final int scan_icon=0x7f020079;
        public static final int scan_list2_icon=0x7f02007a;
        public static final int scan_list_icon=0x7f02007b;
        public static final int scicsors_big=0x7f02007c;
        public static final int scicsors_big_bottom=0x7f02007d;
        public static final int scicsors_big_top=0x7f02007e;
        public static final int scicsors_small=0x7f02007f;
        public static final int search44b=0x7f020080;
        public static final int search54b=0x7f020081;
        public static final int search64b=0x7f020082;
        public static final int search_contacts_54_black=0x7f020083;
        public static final int security=0x7f020084;
        public static final int shape_alert_dot_border=0x7f020085;
        public static final int shape_clear_cut_dot_border=0x7f020086;
        public static final int shape_clear_dot_border=0x7f020087;
        public static final int shape_cream=0x7f020088;
        public static final int shape_info_dot_border=0x7f020089;
        public static final int shape_orange=0x7f02008a;
        public static final int shape_red=0x7f02008b;
        public static final int shape_silver=0x7f02008c;
        public static final int shape_silver_dot_border=0x7f02008d;
        public static final int shape_silver_no_border=0x7f02008e;
        public static final int shape_success_cut_dot_border=0x7f02008f;
        public static final int shape_success_dot_border=0x7f020090;
        public static final int shape_voucher=0x7f020091;
        public static final int shape_voucher_list_green=0x7f020092;
        public static final int shape_voucher_list_grey=0x7f020093;
        public static final int shape_voucher_list_red=0x7f020094;
        public static final int shape_warning_dot_border=0x7f020095;
        public static final int silver_button=0x7f020096;
        public static final int sort54=0x7f020097;
        public static final int sort64=0x7f020098;
        public static final int success=0x7f020099;
        public static final int toolbar_button=0x7f02009a;
        public static final int toolbar_button_black_degraded=0x7f02009b;
        public static final int toolbar_button_white=0x7f02009c;
        public static final int transfer=0x7f02009d;
        public static final int transparent_button=0x7f02009e;
        public static final int unlock64=0x7f02009f;
        public static final int viewvoucher54=0x7f0200a0;
        public static final int voucher2_icon=0x7f0200a1;
        public static final int voucher_icon=0x7f0200a2;
        public static final int voucher_list_item_degraded=0x7f0200a3;
        public static final int voucherlistitem_03=0x7f0200a4;
        public static final int warning_48=0x7f0200a5;
        public static final int yellow_button=0x7f0200a6;
    }
    public static final class id {
        public static final int TextView01=0x7f090027;
        public static final int TextView03=0x7f090048;
        /**  Messages IDs 
         */
        public static final int auto_focus=0x7f090000;
        public static final int beneficiary=0x7f090063;
        public static final int bottom_menu=0x7f090030;
        public static final int btnBack=0x7f090023;
        public static final int btnLinkToLoginScreen=0x7f09003d;
        public static final int btnLogin=0x7f090035;
        public static final int btnLogout=0x7f090058;
        public static final int btnPasswordRecovery=0x7f090037;
        public static final int btnRegister=0x7f09003c;
        public static final int conditionsLayout=0x7f090047;
        public static final int contactsButton=0x7f090029;
        public static final int contents_text_view=0x7f090061;
        public static final int currencyText=0x7f09005d;
        public static final int daysLeft=0x7f090064;
        public static final int decode=0x7f090001;
        public static final int decode_failed=0x7f090002;
        public static final int decode_succeeded=0x7f090003;
        public static final int delete=0x7f090041;
        public static final int deleteButton=0x7f09004c;
        public static final int description=0x7f090071;
        public static final int detailsLayout=0x7f090046;
        public static final int discountDate=0x7f090070;
        public static final int discount_layout=0x7f090054;
        public static final int emailAddress=0x7f09004f;
        public static final int emailBox=0x7f090028;
        public static final int encode_failed=0x7f090004;
        public static final int encode_succeeded=0x7f090005;
        public static final int encode_view=0x7f09005f;
        public static final int firstName=0x7f09002b;
        public static final int flipper=0x7f090042;
        public static final int footer_1=0x7f090068;
        public static final int footer_layout=0x7f090067;
        public static final int foundMessage=0x7f09002a;
        public static final int fullscreen_content=0x7f09000c;
        public static final int fullscreen_content_controls=0x7f09000d;
        public static final int image1=0x7f09005e;
        public static final int imageView1=0x7f090011;
        public static final int imageView10=0x7f09001a;
        public static final int imageView11=0x7f09001b;
        public static final int imageView12=0x7f09001e;
        public static final int imageView13=0x7f090020;
        public static final int imageView2=0x7f090012;
        public static final int imageView3=0x7f090013;
        public static final int imageView4=0x7f090014;
        public static final int imageView5=0x7f090015;
        public static final int imageView6=0x7f090016;
        public static final int imageView7=0x7f090017;
        public static final int imageView8=0x7f090018;
        public static final int imageView9=0x7f090019;
        public static final int image_view=0x7f090060;
        public static final int info=0x7f09003e;
        public static final int issuer=0x7f09006f;
        public static final int lastName=0x7f09002c;
        public static final int launchButton=0x7f09002e;
        public static final int launch_product_query=0x7f090006;
        public static final int linearLayout2=0x7f090026;
        public static final int list=0x7f09002f;
        public static final int lock=0x7f09003f;
        public static final int loginEmail=0x7f090033;
        public static final int loginPassword=0x7f090034;
        public static final int login_error=0x7f090036;
        public static final int mainLayout=0x7f090025;
        public static final int main_layout=0x7f09000f;
        public static final int main_menu=0x7f090053;
        public static final int menu_settings=0x7f090073;
        public static final int message=0x7f090069;
        public static final int message2=0x7f090049;
        public static final int message3=0x7f09004a;
        public static final int message_bottom=0x7f09006d;
        public static final int myAccount=0x7f090057;
        public static final int ok_button=0x7f09006e;
        public static final int password_edit=0x7f09006c;
        public static final int permissionCheckBox=0x7f09002d;
        public static final int pin=0x7f09004d;
        public static final int preview_view=0x7f090050;
        public static final int prueba=0x7f090055;
        public static final int qrImage=0x7f09000e;
        public static final int qrLayout=0x7f090044;
        public static final int quit=0x7f090007;
        public static final int registerEmail=0x7f090039;
        public static final int registerName=0x7f090038;
        public static final int registerPassword=0x7f09003a;
        public static final int register_error=0x7f09003b;
        public static final int restart_preview=0x7f090008;
        public static final int return_scan_result=0x7f090009;
        public static final int saveButton=0x7f09004e;
        public static final int scroll=0x7f090024;
        public static final int search=0x7f090032;
        public static final int search_book_contents_failed=0x7f09000a;
        public static final int search_book_contents_succeeded=0x7f09000b;
        public static final int settings_layout=0x7f090056;
        public static final int sort=0x7f090031;
        public static final int statusText=0x7f090066;
        public static final int text1=0x7f09005a;
        public static final int text3=0x7f09005c;
        public static final int text4=0x7f09005b;
        public static final int textView1=0x7f09001c;
        public static final int textView2=0x7f09001d;
        public static final int textView3=0x7f090010;
        public static final int textView4=0x7f09001f;
        public static final int textView5=0x7f090021;
        public static final int title=0x7f090062;
        public static final int toast_holder=0x7f090052;
        public static final int top_menu=0x7f090022;
        public static final int transfer=0x7f090040;
        public static final int transferButton=0x7f09004b;
        public static final int username_edit=0x7f09006a;
        public static final int username_fixed=0x7f09006b;
        public static final int value=0x7f090065;
        public static final int viewfinder_view=0x7f090051;
        public static final int voucherImage=0x7f090045;
        public static final int voucherLayout=0x7f090043;
        public static final int voucher_delete=0x7f090072;
        public static final int voucher_info=0x7f090074;
        public static final int voucher_list_item=0x7f090059;
        public static final int voucher_lock=0x7f090075;
        public static final int voucher_transfer=0x7f090076;
    }
    public static final class layout {
        public static final int activity_barcode=0x7f030000;
        public static final int activity_dashboard=0x7f030001;
        public static final int activity_discount=0x7f030002;
        public static final int activity_fast__launch__step2=0x7f030003;
        public static final int activity_identity_alert=0x7f030004;
        public static final int activity_launch_voucher=0x7f030005;
        public static final int activity_launchedvoucher=0x7f030006;
        public static final int activity_launchedvoucherslist=0x7f030007;
        public static final int activity_login=0x7f030008;
        public static final int activity_pin_interface=0x7f030009;
        public static final int activity_register=0x7f03000a;
        public static final int activity_scan=0x7f03000b;
        public static final int activity_scanedvoucherslist=0x7f03000c;
        public static final int activity_scanned_voucher=0x7f03000d;
        public static final int activity_voucher=0x7f03000e;
        public static final int activity_voucher_delete=0x7f03000f;
        public static final int activity_voucher_pin=0x7f030010;
        public static final int activity_voucher_transfer=0x7f030011;
        public static final int activity_voucherslist=0x7f030012;
        public static final int capture=0x7f030013;
        public static final int copy_of_activity_dashboard=0x7f030014;
        public static final int copy_of_voucher_list_item=0x7f030015;
        public static final int encode=0x7f030016;
        public static final int launched_voucher_list_item=0x7f030017;
        public static final int list_footer_view=0x7f030018;
        public static final int login_activity=0x7f030019;
        public static final int main=0x7f03001a;
        public static final int scanned_voucher_list_item=0x7f03001b;
        public static final int template_list_item=0x7f03001c;
        public static final int voucher_list_item=0x7f03001d;
    }
    public static final class menu {
        public static final int activity_capture=0x7f0b0000;
        public static final int activity_discount=0x7f0b0001;
        public static final int activity_fast__launch__step2=0x7f0b0002;
        public static final int activity_identity_alert=0x7f0b0003;
        public static final int activity_launch_voucher=0x7f0b0004;
        public static final int activity_pin_interface=0x7f0b0005;
        public static final int activity_register=0x7f0b0006;
        public static final int activity_voucher=0x7f0b0007;
        public static final int activity_voucher_delete=0x7f0b0008;
        public static final int activity_voucher_pin=0x7f0b0009;
        public static final int activity_voucher_pin_reset=0x7f0b000a;
        public static final int activity_voucher_transfer=0x7f0b000b;
    }
    public static final class raw {
        public static final int beep=0x7f060000;
    }
    public static final class string {
        public static final int Launch_Voucher=0x7f070009;
        public static final int My_Vouchers=0x7f070007;
        public static final int Scan_Vouchers=0x7f070008;
        public static final int already_registered=0x7f07001a;
        public static final int app_name=0x7f070000;
        /**  Button for going to the previous screen or step 
         */
        public static final int back_button_label=0x7f070035;
        public static final int blank_label=0x7f07003b;
        /**  Button to cancel the current operation 
         */
        public static final int cancel_button_label=0x7f070036;
        public static final int contents_contact=0x7f07003d;
        public static final int contents_email=0x7f07003e;
        public static final int contents_location=0x7f07003f;
        public static final int contents_phone=0x7f070040;
        public static final int contents_sms=0x7f070041;
        public static final int contents_text=0x7f07003c;
        public static final int dummy_button=0x7f070047;
        public static final int dummy_content=0x7f070046;
        public static final int error_config=0x7f070019;
        public static final int gcm_deleted=0x7f070020;
        public static final int gcm_error=0x7f07001e;
        public static final int gcm_message=0x7f07001d;
        public static final int gcm_recoverable_error=0x7f07001f;
        public static final int gcm_registered=0x7f07001b;
        public static final int gcm_unregistered=0x7f07001c;
        public static final int hello_world=0x7f070003;
        public static final int label=0x7f07002a;
        /**  Message shown in dialog if the username or password is invalid. 
         */
        public static final int login_activity_loginfail_text_both=0x7f070030;
        /**  Message shown in dialog to prompt the user for their password 
         */
        public static final int login_activity_loginfail_text_pwmissing=0x7f070032;
        /**  Message shown in dialog if the password is invalid 
         */
        public static final int login_activity_loginfail_text_pwonly=0x7f070031;
        /** 
        Message shown if the provided account doesn't support the current
        activity.
    
         */
        public static final int login_activity_newaccount_text=0x7f070033;
        /**  Button to sign in after entering username and password 
         */
        public static final int login_activity_ok_button=0x7f07002f;
        /**  Label above password EditText 
         */
        public static final int login_activity_password_label=0x7f07002e;
        /**  Label above username EditText 
         */
        public static final int login_activity_username_label=0x7f07002d;
        public static final int manual_button_label=0x7f07003a;
        public static final int menu_settings=0x7f070017;
        public static final int msg_default_status=0x7f070039;
        public static final int options_clear=0x7f070028;
        public static final int options_exit=0x7f070029;
        public static final int options_register=0x7f070026;
        public static final int options_unregister=0x7f070027;
        public static final int profile_action=0x7f070037;
        public static final int scan=0x7f070001;
        public static final int scan_only_qr_codes=0x7f070002;
        public static final int server_register_error=0x7f070024;
        public static final int server_registered=0x7f070022;
        public static final int server_registering=0x7f070021;
        public static final int server_unregister_error=0x7f070025;
        public static final int server_unregistered=0x7f070023;
        /**  Button that takes the user to the "sign in" screen 
         */
        public static final int sign_in_button_label=0x7f070034;
        public static final int title_activity_barcode=0x7f070048;
        public static final int title_activity_dashboard=0x7f070006;
        public static final int title_activity_discount=0x7f07000b;
        public static final int title_activity_fast__launch__step2=0x7f070015;
        public static final int title_activity_identity_alert=0x7f07000c;
        public static final int title_activity_launch_voucher=0x7f070014;
        public static final int title_activity_launched_voucher=0x7f070016;
        public static final int title_activity_login=0x7f070004;
        public static final int title_activity_main=0x7f070018;
        public static final int title_activity_pin_interface=0x7f07000d;
        public static final int title_activity_register=0x7f070005;
        public static final int title_activity_scan=0x7f07000a;
        public static final int title_activity_voucher=0x7f07000f;
        public static final int title_activity_voucher_delete=0x7f070011;
        public static final int title_activity_voucher_pin=0x7f070012;
        public static final int title_activity_voucher_pin_reset=0x7f070013;
        public static final int title_activity_voucher_transfer=0x7f070010;
        public static final int title_activity_voucherslist=0x7f07000e;
        /**  Message shown in progress dialog while app connects to the server 
         */
        public static final int ui_activity_authenticating=0x7f07002c;
        public static final int ui_activity_title=0x7f07002b;
        public static final int view_profile=0x7f070038;
        public static final int voucher_delete=0x7f070045;
        public static final int voucher_info=0x7f070042;
        public static final int voucher_lock=0x7f070043;
        public static final int voucher_transfer=0x7f070044;
    }
    public static final class style {
        public static final int ButtonBar=0x7f0a0009;
        public static final int ButtonBarButton=0x7f0a0008;
        public static final int ButtonText=0x7f0a0000;
        public static final int FullscreenActionBarStyle=0x7f0a000b;
        public static final int FullscreenTheme=0x7f0a000a;
        public static final int autoscroll=0x7f0a0005;
        public static final int autoscroll2=0x7f0a0006;
        public static final int loadMoreButton=0x7f0a0007;
        public static final int logOutButton=0x7f0a0004;
        public static final int mediumButtonText=0x7f0a0002;
        public static final int mediumButtonTextBlack=0x7f0a0003;
        public static final int smallButtonText=0x7f0a0001;
    }
    public static final class xml {
        public static final int authenticator=0x7f050000;
    }
    public static final class styleable {
        /** 
         Declare custom theme attributes that allow changing which styles are
         used for button bars depending on the API level.
         ?android:attr/buttonBarStyle is new as of API 11 so this is
         necessary to support previous API levels.
    
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_buttonBarButtonStyle com.beevou.android:buttonBarButtonStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_buttonBarStyle com.beevou.android:buttonBarStyle}</code></td><td></td></tr>
           </table>
           @see #ButtonBarContainerTheme_buttonBarButtonStyle
           @see #ButtonBarContainerTheme_buttonBarStyle
         */
        public static final int[] ButtonBarContainerTheme = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.beevou.android.R.attr#buttonBarButtonStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:buttonBarButtonStyle
        */
        public static final int ButtonBarContainerTheme_buttonBarButtonStyle = 1;
        /**
          <p>This symbol is the offset where the {@link com.beevou.android.R.attr#buttonBarStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:buttonBarStyle
        */
        public static final int ButtonBarContainerTheme_buttonBarStyle = 0;
    };
}
